export const appconstants = {
    SET_TITLE:"SET_TITLE",
    SET_TITL:"SET_TITL",
    GET_SINGLE:"GET_SINGLE",
    ADD_TO_CART:"ADD_TO_CART",
    USER_REGISTER:"USER_REGISTER",
    SET_ALL_TASKS:"SET_ALL_TASKS",
    APART_REMOVE_SET_TASKS:"APART_REMOVE_SET_TASKS",
    SET_EDIT_TASK:"SET_EDIT_TASK",
    CLICK_CHECKBOX:"CLICK_CHECKBOX"
}